export type BiomeWarning =
  | "WATER_DEFICIT"
  | "WATER_OVERFLOW"
  | "LOW_HUMIDITY"
  | "HIGH_HUMIDITY"
  | "LOW_TEMPERATURE"
  | "HIGH_TEMPERATURE"
  | "HEAT_SURPLUS"
  | "HEAT_DEFICIT"
  | "THERMAL_STORAGE_FULL"
  | "COMPUTE_THROTTLED"
  | "PLANT_STRESS";
