import type { ExternalClimateCondition } from "../domain/air";

export const floridaHumidDay: ExternalClimateCondition[] = [
  { hour: 0, temperatureC: 25, relativeHumidityPct: 92, solarGainWattsPerM2: 0 },
  { hour: 1, temperatureC: 25, relativeHumidityPct: 93, solarGainWattsPerM2: 0 },
  { hour: 2, temperatureC: 24, relativeHumidityPct: 94, solarGainWattsPerM2: 0 },
  { hour: 3, temperatureC: 24, relativeHumidityPct: 95, solarGainWattsPerM2: 0 },
  { hour: 4, temperatureC: 24, relativeHumidityPct: 96, solarGainWattsPerM2: 0 },
  { hour: 5, temperatureC: 24, relativeHumidityPct: 96, solarGainWattsPerM2: 0 },
  { hour: 6, temperatureC: 25, relativeHumidityPct: 94, solarGainWattsPerM2: 50 },
  { hour: 7, temperatureC: 26, relativeHumidityPct: 90, solarGainWattsPerM2: 150 },
  { hour: 8, temperatureC: 28, relativeHumidityPct: 84, solarGainWattsPerM2: 300 },
  { hour: 9, temperatureC: 30, relativeHumidityPct: 76, solarGainWattsPerM2: 500 },
  { hour: 10, temperatureC: 32, relativeHumidityPct: 68, solarGainWattsPerM2: 650 },
  { hour: 11, temperatureC: 33, relativeHumidityPct: 62, solarGainWattsPerM2: 750 },
  { hour: 12, temperatureC: 34, relativeHumidityPct: 58, solarGainWattsPerM2: 800 },
  { hour: 13, temperatureC: 35, relativeHumidityPct: 54, solarGainWattsPerM2: 750 },
  { hour: 14, temperatureC: 35, relativeHumidityPct: 52, solarGainWattsPerM2: 650 },
  { hour: 15, temperatureC: 34, relativeHumidityPct: 55, solarGainWattsPerM2: 500 },
  { hour: 16, temperatureC: 33, relativeHumidityPct: 60, solarGainWattsPerM2: 300 },
  { hour: 17, temperatureC: 32, relativeHumidityPct: 66, solarGainWattsPerM2: 150 },
  { hour: 18, temperatureC: 30, relativeHumidityPct: 74, solarGainWattsPerM2: 50 },
  { hour: 19, temperatureC: 28, relativeHumidityPct: 82, solarGainWattsPerM2: 0 },
  { hour: 20, temperatureC: 27, relativeHumidityPct: 86, solarGainWattsPerM2: 0 },
  { hour: 21, temperatureC: 26, relativeHumidityPct: 89, solarGainWattsPerM2: 0 },
  { hour: 22, temperatureC: 26, relativeHumidityPct: 90, solarGainWattsPerM2: 0 },
  { hour: 23, temperatureC: 25, relativeHumidityPct: 91, solarGainWattsPerM2: 0 },
];

export const arizonaDryDay: ExternalClimateCondition[] = [
  { hour: 0, temperatureC: 22, relativeHumidityPct: 42, solarGainWattsPerM2: 0 },
  { hour: 1, temperatureC: 21, relativeHumidityPct: 44, solarGainWattsPerM2: 0 },
  { hour: 2, temperatureC: 20, relativeHumidityPct: 46, solarGainWattsPerM2: 0 },
  { hour: 3, temperatureC: 19, relativeHumidityPct: 48, solarGainWattsPerM2: 0 },
  { hour: 4, temperatureC: 18, relativeHumidityPct: 50, solarGainWattsPerM2: 0 },
  { hour: 5, temperatureC: 18, relativeHumidityPct: 51, solarGainWattsPerM2: 0 },
  { hour: 6, temperatureC: 19, relativeHumidityPct: 48, solarGainWattsPerM2: 50 },
  { hour: 7, temperatureC: 22, relativeHumidityPct: 40, solarGainWattsPerM2: 150 },
  { hour: 8, temperatureC: 26, relativeHumidityPct: 32, solarGainWattsPerM2: 300 },
  { hour: 9, temperatureC: 30, relativeHumidityPct: 26, solarGainWattsPerM2: 550 },
  { hour: 10, temperatureC: 33, relativeHumidityPct: 22, solarGainWattsPerM2: 700 },
  { hour: 11, temperatureC: 35, relativeHumidityPct: 19, solarGainWattsPerM2: 800 },
  { hour: 12, temperatureC: 37, relativeHumidityPct: 17, solarGainWattsPerM2: 850 },
  { hour: 13, temperatureC: 38, relativeHumidityPct: 16, solarGainWattsPerM2: 800 },
  { hour: 14, temperatureC: 39, relativeHumidityPct: 15, solarGainWattsPerM2: 700 },
  { hour: 15, temperatureC: 39, relativeHumidityPct: 15, solarGainWattsPerM2: 550 },
  { hour: 16, temperatureC: 38, relativeHumidityPct: 16, solarGainWattsPerM2: 350 },
  { hour: 17, temperatureC: 36, relativeHumidityPct: 18, solarGainWattsPerM2: 150 },
  { hour: 18, temperatureC: 33, relativeHumidityPct: 22, solarGainWattsPerM2: 50 },
  { hour: 19, temperatureC: 30, relativeHumidityPct: 26, solarGainWattsPerM2: 0 },
  { hour: 20, temperatureC: 27, relativeHumidityPct: 31, solarGainWattsPerM2: 0 },
  { hour: 21, temperatureC: 25, relativeHumidityPct: 35, solarGainWattsPerM2: 0 },
  { hour: 22, temperatureC: 24, relativeHumidityPct: 38, solarGainWattsPerM2: 0 },
  { hour: 23, temperatureC: 23, relativeHumidityPct: 40, solarGainWattsPerM2: 0 },
];
